OzFlux/PyFluxPro

- .gitignore
- PyFluxPro.py
- scripts/pfp_gui.py
1) added .gitignore from standard PyFluxPro
2) implemented use of changed control file contents
> Implement use of edited control files and added .gitignore.

- PyFluxPro.py
- scripts/pfp_ck.py
- scripts/pfp_plot.py
- scripts/pfp_top_level.py
Also implemented re-use of existing figures to make plotting
more interactive.
> Fixed bug in pfp_ck.do_7500check.

- scripts/pfp_gui.py
Cleaned up the L2 GUI functions to use better methoda for adding and removing items, similar to clean up of L1 functions.
> Clean up L2 GUI functions.

- solo/seqsolo/seqsolo_osx.mak
- solo/sofm/sofm_osx.mak
- solo/solo/solo_osx.mak
> Removed sudo from *_osx.mak files.

- scripts/pfp_ts.py
Propagate changes to pfp_ts.MergeSeries() from PFP Classic to PFP GUI.
MergeSeries() rewritten to use GetVariable() so that convert_units_func() is called correctly.
> Rewrite pfp_ts.MergeSeries() to use pfp_utils.GetVariable().

- PyFluxPro.py
- scripts/pfp_ck.py
- scripts/pfp_func.py
- scripts/pfp_gui.py
- scripts/pfp_levels.py
- scripts/pfp_plot.py
- scripts/pfp_ts.py
- scripts/pfp_utils.py
A number of changes:
1) fixed bugs in L1 functions
2) implemented LowerCheck and UpperCheck QC functions at L2
3) implemented ApplyFcStorage at variable level
4) transfer contents of [General] to [Options]
5) relocate calculation of Monin-Obukhov length to after creation of new series
> Fix bugs in L1 functions.

- PyFluxPro.py
- controlfiles/templates/L6/L6.txt
- scripts/pfp_gui.py
Updated L6 GUI code from old style to new code and fixed some bugs along the way.
> Fix bugs in L6

- controlfiles/templates/L3/L3_ozflux.txt
- environment.yml
- scripts/pfp_gf.py
- scripts/pfp_gui.py
1. Version of timezonefinder pinned to V3.3.0 in environment.yml file
Jupyter removed from environment.yml file,
> Staging commit, timezonefinder version

- scripts/pfp_gui.py
Fix bug in L3 processing.
Implement Imports at L3.
Disable drag and drop in all GUIs.
> Fix Imports at L3.

- scripts/pfp_ck.py
in pfp_ck.py line 571 moved "return" four spaces left to be outside the multiple line "for" loop
> allow multiple lines for each variable using ExcludeDates

- controlfiles/standard/fluxnet.txt
- scripts/pfp_top_level.py
> Implement FluxNet time series plots of data.

- PyFluxPro.py
- scripts/pfp_func.py
- scripts/pfp_plot.py
- scripts/pfp_top_level.py
- scripts/pfp_ts.py
- scripts/pfp_utils.py
> Implemented QuickCheck plots.

- scripts/pfp_mpt.py
Write all statistics output by the MPT code into the results workbook.
> Include all statistics in MPT output file in Excel workbook.

- scripts/pfp_io.py
- scripts/pfp_rp.py
Added the time step as a variable attribute for the time variable in L6 summary files.  This helps with concatenating files.
> Add time_step to time variable attributes in L6 summary files.

- controlfiles/standard/climatology.txt
- controlfiles/templates/L5/L5_MDS.txt
- controlfiles/templates/L5/L5_SOLO.txt
- scripts/pfp_ck.py
- scripts/pfp_gf.py
- scripts/pfp_gfALT.py
- scripts/pfp_gfSOLO.py
- scripts/pfp_gui.py
- scripts/pfp_levels.py
- scripts/pfp_rp.py
- scripts/pfp_rpNN.py
Implemented Imports at L5.  This required adding code to truncate the tower data to the end date of the imported data.  For example, MODIS EVI data is not always up to date with the tower data.  In this case, we truncate the tower data to the MODIS EVI end date so the MODIS EVI can be used as a driver for the neural networks.
> Implement Imports at L5.

- PyFluxPro.py
- scripts/pfp_top_level.py
Trap exceptions by wrapping high levels in try...except clauses and printing exceptions to the Log window.
This is the first step in making PFP more robust.  The next step is to check that all operations have the correct information before they are called.
> Wrap high level routines in try...except.

- scripts/pfp_gf.py
- scripts/pfp_gfALT.py
- scripts/pfp_gfMDS.py
- scripts/pfp_gfSOLO.py
- scripts/pfp_levels.py
Trap plot paths that the user does not have permission to create.
> Fix exception from os.makedir() with plot_path at L5.

- scripts/pfp_rpNN.py
> Trap plot paths the user does not have permission to create at L6.

- controlfiles/templates/L2/L2_ozflux.txt
- scripts/pfp_ck.py
- scripts/pfp_gui.py
> Added disable sonic and IRGA checks, Li-7500A pre and post V6.5.

- scripts/pfp_cpd.py
Current CPD version was failing if the L3 netCDF file ended on YYYY-01-01 00:00.
Temporary fix as suggested by Ian by subtracting the time step from the datetime before using it as the dataframe index.
Also removed references to xlDateTime (not used) and now calculate Year from datetime because Year is not in new-style L3 files.
> Fix orphan year in CPD

- scripts/pfp_levels.py
- scripts/pfp_ts.py
pfp_ts.MergeSeries() and pfp_ts.AverageSeriesByElements() now wrapped into pfp_ts.CombineSeries() in pfp_levels.l3qc().  This allows the user to use MergeSeries or AverageSeriesByElements at L3 as they see fit instead of being forced to a particular method based on the developer's whim.
> Wrap MergeSeries and AverageSeriesByElements into CombineSeries.

- scripts/pfp_rpLL.py
- scripts/pfp_rpLT.py
Used dt in list comprehension and thought it would be independent of the rest of the code.
Not so ...
> Fix bug in LT and LL plts at L6.

- scripts/pfp_top_level.py
Should never happen ...
But it did.
> Handle L2 and L3 control files without [Plots] section.

- scripts/pfp_plot.py
- scripts/pfp_utils.py
Added a colour bar to the plots done under Plots/Summary.
In previous versions, the points in the daily and diurnal plots were coloured based on the number of points used to form the average.  Now they are coloured based on the percebtage of good data used and a colour bar has been added to the plots.
> Changes to pfp_plot.plot_quickcheck()

- scripts/pfp_func.py
- scripts/pfp_plot.py
- scripts/pfp_utils.py
Added a function at L1 to convert soil moisture from percent to m3/m3.
Added a pause between plots in pfp_plot.plot_quickcheck() so plots display before next one started.
> Add function to convert soil moisture from percent to m3/m3.

- scripts/pfp_gfSOLO.py
SOFM/SOLO/SEQSOLO fail if a driver has variance=0.  Drivers now checked and any with var=0 are rejected.
Note for Cacilia: already applied to develop branch.
> Check drivers at L5 and reject if variance=0.

- scripts/pfp_plot.py
XY plots were generated but not displayed.  Changed from fig.show() to plt.draw() as per time series plots.
> Fix XY plot

- utilities/portal_audit.py
Added output to Excel workbook from portal_audit.py.
> Excel output from portal_audit.py

- scripts/pfp_compliance.py
- scripts/pfp_io.py
- scripts/pfp_utils.py
- utilities/portal_audit.py
Variables with more than 75% data were read from the Excel workbook but not written to the data structure.  Rewrote part of pfp_io.ExceltoDataStructures() to better handle missing data in Excel variables.
> Fix read l1 excel

- controlfiles/standard/climatology.txt
- scripts/pfp_compliance.py
- scripts/pfp_io.py
Implemented "Function" at L1 in pfp_compliance.py.
Fixed QC flag warnings at L1.
> Fix Function and L1 QC flag warnings

- scripts/pfp_ts.py
> Suppress warnings from pfp_ts.CombineSeries() by default.

- scripts/pfp_ck.py
- scripts/pfp_gui.py
Completed implementation of Li-7200/Li-7200RS IRGA type.
> Implement Li-7200 IRGA type

- scripts/pfp_gui.py
Enable drag and drop for L4, L5 and L6 GUIs.
> Enable drag and drop for L4, L5 and L6 GUIs

- scripts/pfp_gfSOLO.py
- scripts/pfp_gui.py
- scripts/pfp_io.py
Implemented Imports section at L5 GUI.
Implemented KeepIntermediateSeries in L5 Options section.
Implemented myTreeView (subclass of QTreeView) to get desired drag and drop behaviour.
> Fix l5 imports options

- scripts/pfp_gui.py
> Cleaning up the code, removing comments.

- scripts/pfp_ck.py
- scripts/pfp_gui.py
- scripts/pfp_rp.py
Changing ustar filter names to:
1. "ustar" - basic ustar filter, remove Fc when ustar < threshold
1. "ustar (EvGb)" - Eva van Gorsel Method B (unpublished), accept nocturnal Fc after sunset as long as ustar >= threshold, reject nocturnal Fc once ustar < threshold
1. "L" - filter on Monin-Obukhov length
> Change 'ustar_persist' to 'ustar (EvGb)'
